services:
  postgres:
    image: postgres:15-alpine
    container_name: moto_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moto_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: moto_backend
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: "postgresql://user:password@postgres:5432/moto_service?sslmode=disable"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: moto_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080/api/v1"
    depends_on:
      - backend

volumes:
  postgres_data: